name: Tests

on:
  pull_request:
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

  generate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - run: make generate
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'make generate' command and commit."; exit 1)

  test-terraform:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    strategy:
      # acceptances tests are not parallelizable
      # culprit : workflows_data_source_test.go (count of workflows in the organization),
      # workflow_resource_test.go : for the issue tests and the hardcoded fcm integration identifier)
      max-parallel: 1
      fail-fast: false
      matrix:
        terraform:
          - "1.14.*"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - env:
          NOVU_API_KEY: ${{ secrets.NOVU_TEST_ORG_DEV_API_KEY }}
        run: make provider-testacc
        timeout-minutes: 10

  test-opentofu:
    name: OpenTofu Provider Acceptance Tests
    needs: [build, test-terraform] # because no parallelizable tests
    if: always() && needs.build.result == 'success'
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    strategy:
      # acceptances tests are not parallelizable, see test-terraform
      max-parallel: 1
      fail-fast: false
      matrix:
        tofu:
          - "1.11.*"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ matrix.tofu }}
      - name: Locate tofu path
        id: tofu-path
        run: |
          echo "tofu_path=$(which tofu)" >> "${GITHUB_OUTPUT}"
      - run: go mod download
      - env:
          NOVU_API_KEY: ${{ secrets.NOVU_TEST_ORG_DEV_API_KEY }}
        run: make provider-testacc-tofu
        timeout-minutes: 10
